### PR TITLE
Draft: feat: use alby-js-sdk client (WIP)

### PR DESCRIPTION
**Pull request by rolznz**

### CODE REVIEW

**Comment by pavanjoshi914** [comment]
is there any blocker in this part of code? as you mentioned TODO. ```authClient.isAccessTokenexpired()``` will do the job here right?

```
  if (this.config.oAuthToken) {
        console.info("Requesting new oAuth token");
        try {
          // TODO: only do this if access token has expired
          console.log(authClient);
          const token = await authClient.refreshAccessToken();
          await this._updateOAuthToken(token.token);
          console.log(authClient);
          
          return authClient;
        } catch (error) {
          console.error("Failed to request new auth token", error);
        }
      }
     ```

**Comment by pavanjoshi914** [comment]
image

i am always geting such symbol

**Comment by pavanjoshi914** [comment]
how the authroize function is handling refresh token expiry?

**Comment by pavanjoshi914** [comment]
i have to authroize everytime for eg. switching between accounts. code is not using existing config data

**Comment by rolznz** [comment]
> how the authroize function is handling refresh token expiry?

if requesting a new access token fails we know the refresh token is invalid

**Comment by rolznz** [comment]
> image
> 
> i am always geting such symbol

Ah, I see this happens if you have no lightning address. Fixed, it will use "Alby" as the default like you previously had

**Pull request merged**
